### ISSUE TITLE
Tab Redirect Card does not hide when user defines secondary tab

### ISSUE THREAD

**Issue by xbmcnut** [ben8p/lovelace-tab-redirect-card#3]
Hey Ben,

Confusing title I know. Seems that when I set the user to have the default dashboard (under user profile) to the new (tablets) dashboard I created, the tab redirect cards reappear and take up space again. I have several of your cards configured on a secondary dashboard that works well now, but it seems, only as long as I have the users profile set to 'default' dashboard and then select my 'tablets' dashboard with your cards in it.

Setting the users profile to have the default dashboard as my 'tablets' dash, blank (tab-redirect) cards reappear and take up space.

I want to have the tablets dashboard as the default so I can use Fully Kiosk App to restart the Home Assistant app after HA boot as my camera images never load until the app is closed and re-opened.

That all make sense?

**Comment by ben8p** [comment]
Hi,
I understand.
I think it has to do with the latest front-end changes deployed with the latest lovelace.

I am searching for a fix

**Comment by ben8p** [comment]
nevermind, I found the problem. Should be fixed with next update

**Comment by xbmcnut** [comment]
Awesome, thank you.
